// Thai desktop locale
// Translations provided by native speakers. Keys mirror en.ts exactly.
export const dict = {
  "desktop.menu.checkForUpdates": "ตรวจสอบการอัปเดต...",
  "desktop.menu.installCli": "ติดตั้ง CLI...",
  "desktop.menu.reloadWebview": "โหลด Webview ใหม่",
  "desktop.menu.restart": "เริ่มใหม่",
  "desktop.menu.app": "LibreCode",
  "desktop.menu.file": "ไฟล์",
  "desktop.menu.edit": "แก้ไข",
  "desktop.menu.view": "มุมมอง",
  "desktop.menu.help": "ช่วยเหลือ",
  "desktop.menu.file.newSession": "เซสชันใหม่",
  "desktop.menu.file.openProject": "เปิดโปรเจกต์...",
  "desktop.menu.view.toggleSidebar": "สลับแถบข้าง",
  "desktop.menu.view.toggleTerminal": "สลับเทอร์มินัล",
  "desktop.menu.view.toggleFileTree": "สลับทรีไฟล์",
  "desktop.menu.view.back": "ย้อนกลับ",
  "desktop.menu.view.forward": "ไปข้างหน้า",
  "desktop.menu.view.previousSession": "เซสชันก่อนหน้า",
  "desktop.menu.view.nextSession": "เซสชันถัดไป",
  "desktop.menu.help.documentation": "เอกสาร LibreCode",
  "desktop.menu.help.supportForum": "ฟอรัมสนับสนุน",
  "desktop.menu.help.shareFeedback": "แบ่งปันความคิดเห็น",
  "desktop.menu.help.reportBug": "รายงานข้อผิดพลาด",

  "desktop.dialog.chooseFolder": "เลือกโฟลเดอร์",
  "desktop.dialog.chooseFile": "เลือกไฟล์",
  "desktop.dialog.saveFile": "บันทึกไฟล์",

  "desktop.updater.checkFailed.title": "ตรวจสอบการอัปเดตไม่สำเร็จ",
  "desktop.updater.checkFailed.message": "ไม่สามารถตรวจสอบการอัปเดตได้",
  "desktop.updater.none.title": "ไม่มีการอัปเดต",
  "desktop.updater.none.message": "คุณกำลังใช้ LibreCode เวอร์ชันล่าสุด",
  "desktop.updater.downloadFailed.title": "การอัปเดตล้มเหลว",
  "desktop.updater.downloadFailed.message": "ไม่สามารถดาวน์โหลดการอัปเดตได้",
  "desktop.updater.downloaded.title": "ดาวน์โหลดการอัปเดตแล้ว",
  "desktop.updater.downloaded.prompt":
    "LibreCode เวอร์ชัน {{version}} ถูกดาวน์โหลดแล้ว ต้องการติดตั้งและเริ่มใหม่หรือไม่?",
  "desktop.updater.installFailed.title": "การอัปเดตล้มเหลว",
  "desktop.updater.installFailed.message": "ไม่สามารถติดตั้งการอัปเดตได้",

  "desktop.cli.installed.title": "ติดตั้ง CLI แล้ว",
  "desktop.cli.installed.message":
    "ติดตั้ง CLI ไปที่ {{path}}\n\nเริ่มเทอร์มินัลใหม่เพื่อใช้คำสั่ง 'librecode'",
  "desktop.cli.failed.title": "การติดตั้งล้มเหลว",
  "desktop.cli.failed.message": "ติดตั้ง CLI ไม่สำเร็จ: {{error}}",
  "desktop.cli.error.unsupportedPlatform": "รองรับการติดตั้ง CLI เฉพาะบน macOS และ Linux",
  "desktop.cli.error.sidecarMissing": "ไม่พบไบนารี LibreCode CLI โปรดลองติดตั้งแอปเดสก์ท็อปใหม่",
  "desktop.cli.error.scriptWriteFailed": "ไม่สามารถสร้างสคริปต์ติดตั้ง CLI",
  "desktop.cli.error.scriptPermissionFailed": "ไม่สามารถตั้งสิทธิ์ดำเนินการให้สคริปต์ติดตั้ง CLI",
  "desktop.cli.error.scriptRunFailed": "ไม่สามารถเรียกใช้สคริปต์ติดตั้ง CLI",
  "desktop.cli.error.scriptFailed": "สคริปต์ติดตั้ง CLI ล้มเหลว",
  "desktop.cli.error.installPathUnknown": "ไม่สามารถระบุตำแหน่งติดตั้ง CLI",
  "desktop.cli.error.unknown": "ข้อผิดพลาดในการติดตั้งที่ไม่ทราบสาเหตุ",

  "desktop.loading.status.initial": "สักครู่...",
  "desktop.loading.status.done": "เสร็จสิ้น",
  "desktop.loading.status.migrating": "กำลังย้ายฐานข้อมูลของคุณ",
  "desktop.loading.status.waiting": "อาจใช้เวลาสักครู่",
  "desktop.loading.progressAria": "ความคืบหน้าการย้ายฐานข้อมูล",

  "desktop.server.local": "เซิร์ฟเวอร์ท้องถิ่น",
}
