// Turkish desktop locale
// Translations provided by native speakers. Keys mirror en.ts exactly.
export const dict = {
  "desktop.menu.checkForUpdates": "Güncellemeleri Kontrol Et...",
  "desktop.menu.installCli": "CLI Yükle...",
  "desktop.menu.reloadWebview": "Webview'i Yeniden Yükle",
  "desktop.menu.restart": "Yeniden Başlat",
  "desktop.menu.app": "LibreCode",
  "desktop.menu.file": "Dosya",
  "desktop.menu.edit": "Düzenle",
  "desktop.menu.view": "Görünüm",
  "desktop.menu.help": "Yardım",
  "desktop.menu.file.newSession": "Yeni Oturum",
  "desktop.menu.file.openProject": "Proje Aç...",
  "desktop.menu.view.toggleSidebar": "Kenar Çubuğunu Aç/Kapat",
  "desktop.menu.view.toggleTerminal": "Terminali Aç/Kapat",
  "desktop.menu.view.toggleFileTree": "Dosya Ağacını Aç/Kapat",
  "desktop.menu.view.back": "Geri",
  "desktop.menu.view.forward": "İleri",
  "desktop.menu.view.previousSession": "Önceki Oturum",
  "desktop.menu.view.nextSession": "Sonraki Oturum",
  "desktop.menu.help.documentation": "LibreCode Belgeleri",
  "desktop.menu.help.supportForum": "Destek Forumu",
  "desktop.menu.help.shareFeedback": "Geri Bildirim Paylaş",
  "desktop.menu.help.reportBug": "Hata Bildir",

  "desktop.dialog.chooseFolder": "Klasör seçin",
  "desktop.dialog.chooseFile": "Dosya seçin",
  "desktop.dialog.saveFile": "Dosyayı kaydet",

  "desktop.updater.checkFailed.title": "Güncelleme Kontrolü Başarısız",
  "desktop.updater.checkFailed.message": "Güncellemeler kontrol edilemedi",
  "desktop.updater.none.title": "Güncelleme Yok",
  "desktop.updater.none.message": "Zaten LibreCode'un en son sürümünü kullanıyorsunuz",
  "desktop.updater.downloadFailed.title": "Güncelleme Başarısız",
  "desktop.updater.downloadFailed.message": "Güncelleme indirilemedi",
  "desktop.updater.downloaded.title": "Güncelleme İndirildi",
  "desktop.updater.downloaded.prompt":
    "LibreCode sürüm {{version}} indirildi. Yüklemek ve yeniden başlatmak ister misiniz?",
  "desktop.updater.installFailed.title": "Güncelleme Başarısız",
  "desktop.updater.installFailed.message": "Güncelleme yüklenemedi",

  "desktop.cli.installed.title": "CLI Yüklendi",
  "desktop.cli.installed.message":
    "CLI {{path}} konumuna yüklendi.\n\n'librecode' komutunu kullanmak için terminalinizi yeniden başlatın.",
  "desktop.cli.failed.title": "Yükleme Başarısız",
  "desktop.cli.failed.message": "CLI yüklenemedi: {{error}}",
  "desktop.cli.error.unsupportedPlatform": "CLI yüklemesi yalnızca macOS ve Linux'ta desteklenir.",
  "desktop.cli.error.sidecarMissing": "LibreCode CLI ikili dosyası eksik. Masaüstü uygulamasını yeniden yüklemeyi deneyin.",
  "desktop.cli.error.scriptWriteFailed": "CLI yükleyici betiği hazırlanamadı.",
  "desktop.cli.error.scriptPermissionFailed": "CLI yükleyici betiği çalıştırılabilir yapılamadı.",
  "desktop.cli.error.scriptRunFailed": "CLI yükleyici betiği çalıştırılamadı.",
  "desktop.cli.error.scriptFailed": "CLI yükleyici başarısız oldu.",
  "desktop.cli.error.installPathUnknown": "CLI'nin nereye yüklendiği belirlenemedi.",
  "desktop.cli.error.unknown": "Bilinmeyen yükleme hatası",

  "desktop.loading.status.initial": "Bir an...",
  "desktop.loading.status.done": "Tamamlandı",
  "desktop.loading.status.migrating": "Veritabanınız taşınıyor",
  "desktop.loading.status.waiting": "Bu birkaç dakika sürebilir",
  "desktop.loading.progressAria": "Veritabanı taşıma ilerlemesi",

  "desktop.server.local": "Yerel Sunucu",
}
